### ISSUE TITLE
Cron Interval

### ISSUE THREAD

**Issue by amcdnl** [xpepermint/mongodb-cron#1]
The `sleepUntil` property is required when defining cron jobs but never documented. I think it shouldn't be required to specifically declare it null if possible, if not then docs should be added.

**Comment by xpepermint** [comment]
Let me check this ...

**Comment by xpepermint** [comment]
Hum... there is a guided documentation as part of the [README.md](https://github.com/xpepermint/mongodb-cron#one-time-jobs). It says:

> A job should have at least the sleepUntil field. Cron processes only documents where this field exists, other documents are ignored.

Btw, you can rename this field as explains in the [api](https://github.com/xpepermint/mongodb-cron#api) and thus have multiple cron queues on the same collection.

Is that what you were searching? Still anything missing?
