### ISSUE TITLE
Question regarding CPU usage when cron activated

### ISSUE THREAD

**Issue by MeowsterEric** [xpepermint/mongodb-cron#11]
When I activate the cron in the application, the CPU usage on this process is actively showing between 20% - 25%. If I disable the cron, then the usage drop to 0.
The application is running in a test environment, and no other activities happens.

Is this the expected behaviour?
I am using pm2 (v3.5.1) to monit the cpu usage. ($ top -c shows the same CPU usage report)

Btw, thanks for your great work!

**Comment by xpepermint** [comment]
Yes, you should see CPU usage but depends on your computer configuration. 20% is pretty high and I assume you have only 1 CPU.

**Comment by MeowsterEric** [comment]
The application is running in a 2 core vm.
Is there any way to reduce the CPU usage? and what is the expected cpu usage for a 2/4 core machine?

**Comment by xpepermint** [comment]
Yes, change the default configuration parameters.
