### ISSUE TITLE
cron not activated when idleDelay flag set

### ISSUE THREAD

**Issue by MeowsterEric** [xpepermint/mongodb-cron#12]
When I add the idleDelay flag in the configuration and start the application, the worker does not process any queued jobs, even it has passed the defined sleepUntil time.

If the idleDelay flag is removed from configuration, the job is being processed correctly, however, it consume about 12% - 15% CPU usage when cron activated.

I set all queued one-time job to be processed at 5pm everyday, and I wish the cron to be active at approximately 5 mins before job start, so this will reduce my CPU usage over the day time.

Code snippet
```javascript
// mongoose schema
const schema = new mongoose.Schema({
    ... ...
    sleepUntil: {type: Date, required: true, index: true, default: (5pm every day)},
    autoRemove: {type: Boolean, default: true} 

}, {collection: 'Queue'});


// cron setting
const config = {
    collection: db.collection('Queue'),
    onDocument: (async (doc) => { return console.info(doc); }),
    onStart: (async () => { return console.info('cron started.'); }),
    onStop: (async () => { return console.warn('cron has stopped.'); }),
    idleDelay: 60 * 1000  // 1 min delay
};
return new MongoCron(config);
```

**Comment by alpertuna** [comment]
Hi, to reduce cpu consuming you should set `nextDelay`. For example; `{ ..., nextDelay: 1000, ... }`. Otherwise it checks jobs continuously for each js tick.
