### ISSUE TITLE
Any way to add a priority/hierarchy to each job?

### ISSUE THREAD

**Issue by tim-103** [xpepermint/mongodb-cron#21]
Love this package BTW, been using it for a long time for my job processing however I'm now in need of a priority/hierarchy of jobs.

For example I want a certain job type to always execute immediately, before other job types - even if there's a backlog of jobs of other types.

Is this possible at all? I saw in another answer you wrote something about if you change sleepUntil to another value you can have different queues - not sure if this could be applied somehow?

Thanks!

**Comment by xpepermint** [comment]
Yes, you can do this by using a custom [condition](https://github.com/xpepermint/mongodb-cron#api).

**Comment by tim-103** [comment]
> Yes, you can do this by using a custom [condition](https://github.com/xpepermint/mongodb-cron#api).

Thanks, but I'm not sure how adding a condition would work. Is there some way to add a condition that would sort the results, so it could always grab a certain type of job first?

If you had any example that would be awesome! Otherwise I simply have to create another cron & another collection.

**Comment by xpepermint** [comment]
Sorry for closing it too early. Well, we could add a `sort` option the same way I did for the `condition`. A PR would be needed and tests should be included.

What you can do without the PR is simply start a separated queue with a new collection or use the same collection with a custom `condition` read by two different queue processes.

**Comment by tim-103** [comment]
"What you can do without the PR is simply start a separated queue with a new collection or use the same collection with a custom condition read by two different queue processes."

This is a good idea actually! I'm running 100 cron workers, so maybe I'll simply do 50/50. 

Thanks.

**Comment by xpepermint** [comment]
OK, then solved, for now :). Closing ...
