### ISSUE TITLE
[Question] How does this handle if the process isnt running during the time a job was supposed to run?

### ISSUE THREAD

**Issue by jrj2211** [xpepermint/mongodb-cron#31]
This may be something that's just supported inherently by cron but before I start using this would like to know how its handled with this library:

If I schedule a job to run every week to create a new document but my server is down during that time period, does it run the next time the system is started? Does this keep track of when the next run time should be and on bootup check if theres any jobs past their next run time? Or do I need to handle that logic separately?

**Comment by xpepermint** [comment]
I'd have to recheck but to my knowledge, it should automatically resume processing.
